language: node_js
node_js:
  - "0.11"
  - "0.10"
before_script:
  - npm install -g grunt-cli
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0eee8bd7dcb2632328fe
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false


