export const action = {
    CHANGE_ROUTE: "CHANGE_ROUTE",
    UPDATE_CODE: "UPDATE_CODE",
    EXECUTE_CODE: "EXECUTE_CODE",
    EXECUTE_CODE_COMPLETE: "EXECUTE_CODE_COMPLETE",
    CONSOLE_LOG: "CONSOLE_LOG",
    CONSOLE_CLEAR: "CONSOLE_CLEAR",
};